openapi: "3.0.0"
info:
  description: "wikipedia on this day monitoring entity"
  version: "0.0.1"
  title: "wikipedia-mon-entity"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "GPLv2"
    url: "https://www.gnu.org/licenses/gpl-2.0.en.html"

servers:
  - url: /api/v1
    description: "The APIs base path"

tags:
- name: "request"
  description: "A request to a monitoring entity"

paths:
  /request:
    post:
      tags:
      - "request"
      summary: "Get events"
      description: ""
      operationId: "api.wikipedia.getOnThisDay"
      requestBody:
        description: "Monitoring request"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/monitorPayload"
      responses:
        200:
          description: "Event List"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/monitorPayload'

components:
  schemas:
    monitorPayload:
      required:
       - "type"
       - "payload"
      properties:
        type:
          type: "string"
          example: "on_this_day"
        payload:
          type: "object"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"

